### ISSUE TITLE
Research the solution for JSON editor

### ISSUE THREAD

**Issue by zhang4952** [osulp/dcwizard#52]
Prepare for the discussion of development for JSON editor:
- a local development 
- a local development based on existing libraries such as:
> https://github.com/josdejong/jsoneditor
> https://github.com/json-editor/json-editor
- using an existing tool like:
> https://jsoneditoronline.org/

**Comment by sammysamx20** [comment]
https://github.com/json-editor/json-editor this one!

**Comment by zhang4952** [comment]
Investigate two options for web-based JSON editor:
1. Use https://github.com/json-editor/json-editor to create web form for only one questionid and manually assemble the whole database.json
2. Use https://rawgit.com/json-editor/json-editor/master/docs/recursive.html to recursively create JSON for one big question
