### ISSUE TITLE
Improve the final page

### ISSUE THREAD

**Issue by zhang4952** [osulp/dcwizard#57]
- [x] Remove "You are done!" for the final page
- [x] Remove "Final Steps" from the final page (we will have a different label/head)
- [x] Remove "Resources:" if there is no value
- [x] Change "Save" in the "Step Log" to "Download pdf"
- [x] Change "Export" in the final page to "Save to log"
- [x] remove the "Home" in the final page
- [ ] 
![screen shot 2019-02-14 at 3 09 03 pm](https://user-images.githubusercontent.com/609011/52823750-ea795e80-306a-11e9-9b2c-d0f1b9bb43dc.png)
move "Reset" to "Home" in the final page (or remove the "Reset" button)

**Comment by sammysamx20** [comment]
Finished in #61
