### ISSUE TITLE
Improve look-and-feel

### ISSUE THREAD

**Issue by zhang4952** [osulp/dcwizard#58]
- [x] change background of the step log with white background and black font (Removed due to changes)
- [x] use the same font family for all pages/content 
- [x] add date/time (timezone: Pacific Times) and url of the wizard to the step log and downloaded pdf

**Comment by sammysamx20** [comment]
When adding date and time when is it needed?

**Comment by zhang4952** [comment]
Add date and time when people click 'Save to log' button; the url of the Wizard should be 'hard code' in the step log (just like the contact email). These information should also be included in the downloaded pdf.

**Comment by zhang4952** [comment]
Step log will keep black ground with white font because it is pop at the right side of the page.

**Comment by zhang4952** [comment]
Closed via PR#61
