### ISSUE TITLE
Missing question?

### ISSUE THREAD

**Issue by zhang4952** [osulp/dcwizard#63]
Is the missed question caused by a bug or because it is missing in json?
![Screen Shot 2019-03-13 at 4 38 55 PM](https://user-images.githubusercontent.com/609011/54321459-846ef100-45ae-11e9-9abb-c0689745e094.png)

**Comment by sammysamx20** [comment]
This is an information page and is used just to relay info to the readers. This only has one option which is to continue through the Wizard as it only relays info. 

`     {
	         "questionid": "/Q3_1_2_2",
	         "question": "We will explore three circumstances regarding your dataset to help you learn more about different people who can make decisions about your dataset: the existence of data management plans; the funding; other formal documents.",
					 "explanationresources": [""],
			 		"explanationlink": [""],
				   "questionTitle": "Explore three circumstances",
					 	"numoptions": 1,
			     "explanation": "If you are not sure if you or somebody else is the person who gets to make decisions about your dataset, there are a few places that you can check to find the answer. The first one is the Data Management Plan. The second is evaluating where the funding to generate the dataset comes from. The third one is identifying other formal documents that may or may not effect your research project. \n\n  Make sure that you read the explanations because these, more than your questions or answers, will help you learn about decision making in your dataset. ",
	         "optionid1": {
	         "option": "I want to learn more about these three",
	         "nextsteptype": 1,
	         "nextstepcontent": "/Q3_1_2_2_1"

				 }`
