### ISSUE TITLE
Add CSS/HTML config to Json

### ISSUE THREAD

**Issue by zhang4952** [osulp/dcwizard#8]

**Comment by sammysamx20** [comment]
I've already done this by changing the JSON formatting quite a bit. I need to document a lot of those changes. Essentially we can't use google sheets anymore and we need to manually do it now.

**Comment by zhang4952** [comment]
related to #9

**Comment by sammysamx20** [comment]
This is basically done again by me chaning the json file. I'll reopen this issue if we have to change the json if it gets too confusing or some other problem!
