### ISSUE TITLE
Complete the Question and Answer JSON and spreadsheet for the app

### ISSUE THREAD

**Issue by zhang4952** [osulp/dcwizard#9]

**Comment by sammysamx20** [comment]
Clara still hasn't finished the question so this may take a bit

**Comment by sammysamx20** [comment]
Asked Clara about this on 8/13, she said the Me with myself one is taking the longest due to the ambiguity of the questions, it will still be a bit til she is done.

**Comment by sammysamx20** [comment]
She finished them and now just needs editing.
